### ISSUE TITLE
Config for elastic v 7.3.1

### ISSUE THREAD

**Issue by atecey** [jakubhajek/elasticsearch-docker-swarm#3]
I have been trying to get this to work for Elasticsearch + Kibana version 7.3.1.  My master config looks like this.

`bootstrap.memory_lock: true
discovery.seed_hosts: ["tasks.master1", "tasks.master2"]
cluster.initial_master_nodes: ["es-master-1", "es-master-2", "es-master-3"]
node.master: true
node.data: false
node.ingest: false
node.name: es-master-1
cluster.name: "docker-swarm-cluster"
network.host: 0.0.0.0
action.destructive_requires_name: true`

The nodes don't seem to be able to discover each other

`
"stacktrace": ["java.net.UnknownHostException: tasks.esmaster3"
`

Any idea on what im missing?

**Comment by rpresser** [comment]
For what it's worth, I'm having the same problem.

**Comment by jakubhajek** [comment]
Hello! @atecey @rpresser 
it means that Elasticsearch can not resolve the name `tasks.esmaster3`. 

The example config which you have pasted you use different hostnames. 

Would you please share your stack file to see how you defined services?

Thanks!

**Comment by jakubhajek** [comment]
Hi @atecey @rpresser 
The attached config files for Elasticsearch works with Elasticsearch 6.8.x. There are a few crucial changes in 7.x so configurations files have to be updated accordingly.

**Comment by jakubhajek** [comment]
Here is GIST with the basic configuration of Elasticsearch 7.4.2 running on Docker Swarm. 
I will update repository shortly:

https://gist.github.com/jakubhajek/73b36e88a9a85a11b56aa71294e6ef90

I hope that helps to solve your problem with Swarm and Elasticsearch in version 7.x
