### ISSUE TITLE
Question: elasticserach hostname for kibana in swarm mode

### ISSUE THREAD

**Issue by constantx** [jakubhajek/elasticsearch-docker-swarm#4]
Hi @jakubhajek,

I see in the compose file, the kibana service has this `"ELASTICSEARCH_URL=http://data1:9200"`.

I've been trying to setup a swarm cluster as well, and curious how `data1` will be recognized since all the containers in the swarm node has different name?

**Comment by jakubhajek** [comment]
Hi  @constantx 

It is a built-in feature in Docker Swarm. Once you create a cluster you can use the name of the service as a recognizable hostname. I added to my configuration a service name called   [data1](https://github.com/jakubhajek/elasticsearch-docker-swarm/blob/c68997eb2c86e49ab977ff8e18b0ae91e474b143/stack-elastic.yml#L139)

that means that I can point Kibana to connect to this host `data1`. 
It is also true for other services name: master1,  master2, master3, data1, data2, data3, and data4.

Hope that helps, let me know.

**Comment by constantx** [comment]
I thought that's how it works too! Maybe my cluster setup's issue is somewhere else ;) Will recheck.

Thanks @jakubhajek

**Comment by jakubhajek** [comment]
@constantx Let me know if you need support with Docker support :)
