### ISSUE TITLE
elasticsearch:2 master1: Name or service not known

### ISSUE THREAD

**Issue by m1cka** [jakubhajek/elasticsearch-docker-swarm#5]
i started cluster
but i got 3  fails:
   1. [WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade
vm.max_map_count=262144 and LimitMEMLOCK=infinity (added to /usr/lib/systemd/system/docker.service)
but error still  available. (if bootstrap.memory_lock: false)

if if bootstrap.memory_lock: true
WARN ][bootstrap                ] Unable to lock JVM Memory: error=12,reason=Cannot allocate memory
[WARN ][bootstrap                ] This can result in part of the JVM being swapped out.
[WARN ][bootstrap                ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
WARN ][bootstrap                ] These can be adjusted by modifying /etc/security/limits.conf, for example: 
  # allow user 'elasticsearch' mlockall 
elasticsearch soft memlock unlimited 
elasticsearch hard memlock unlimited
added to /etc/security/limits.conf

main problem: -> 
[INFO ][env                      ] [master3] heap size [989.8mb], compressed ordinary object pointers [true]
Exception in thread "main" java.lang.IllegalArgumentException: Failed to resolve address for [master2]
Likely root cause: java.net.UnknownHostException: master2: Name or service not known

its same in all nodes

**Comment by jakubhajek** [comment]
hi @m1cka 

What Elasticsearch version do you try to run?

If you are playing with 7.x you can try my GIST which I just published:

https://gist.github.com/jakubhajek/73b36e88a9a85a11b56aa71294e6ef90

There is an example code to run Elasticsearch 7.4.2 on Docker Swarm.

**Comment by m1cka** [comment]
i'm using elasticsearch 2.4.2,   docker image elasticsearch:2.4.2

**Comment by jakubhajek** [comment]
@m1cka this is a very old version that is no longer supported by the Elastic team. You should consider upgrading to 6.x or 7.x

The code I published here was not tested on such an old version,  so I can't help you until you upgrade to the newest version. 

However, the error you have posted is related to memory locking,  please make sure that Dockerd is started with the parameter` --default-ulimit=memlock -1`

Please let me know if you need support regarding to that upgrade.
