### ISSUE TITLE
Master 1 is not able find the master2 in docker swarm with es cluster

### ISSUE THREAD

**Issue by TamilTintin** [jakubhajek/elasticsearch-docker-swarm#7]
[2020-08-10T14:42:14,401][WARN ][o.e.d.z.UnicastZenPing   ] [es-master1] failed to resolve host [master2]
java.net.UnknownHostException: master2: Name or service not known

**Comment by TamilTintin** [comment]
That was a DNS issues , Solved !

**Comment by recepkabatas** [comment]
How did you do that ?
I had same problem still confused on the problem.

**Comment by TamilTintin** [comment]
For me, the ports for docker swarm is not open, After resolving it, I can achieve

**Comment by EAfang** [comment]
> That was a DNS issues , Solved !

How did you resolve the DNS issue please
